bn_upgradeJavaV4_setupSbt_testing_cache_sbt

diff --git a/.github/workflows/_sbt_jar.yml b/.github/workflows/_sbt_jar.yml
--- a/.github/workflows/_sbt_jar.yml
+++ b/.github/workflows/_sbt_jar.yml
@@ -35,28 +35,27 @@ jobs:
           submodules: true
 
       - name: Setup Java
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: ${{ matrix.java }}
+          cache: sbt
 
-      - name: Setup SBT
-        run: |
-          mkdir -p $HOME/bin/sbt
-          set -eux && curl --fail --silent --location --retry 3 https://github.com/sbt/sbt/releases/download/v1.9.9/sbt-1.9.9.tgz | gunzip | tar x -C $HOME/bin/sbt
-          echo "$HOME/bin/sbt" >> $GITHUB_PATH
-
-      - name: Cache sbt
-        uses: actions/cache@v3
+      - uses: sbt/setup-sbt@v1
         with:
-          path: |
-            ~/.sbt
-            ~/.ivy2/cache
-            ~/.coursier/cache/v1
-            ~/.cache/coursier/v1
-            ~/AppData/Local/Coursier/Cache/v1
-            ~/Library/Caches/Coursier/v1
-          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
+          sbt-runner-version: 1.10.6
+
+#      - name: Cache sbt
+#        uses: actions/cache@v3
+#        with:
+#          path: |
+#            ~/.sbt
+#            ~/.ivy2/cache
+#            ~/.coursier/cache/v1
+#            ~/.cache/coursier/v1
+#            ~/AppData/Local/Coursier/Cache/v1
+#            ~/Library/Caches/Coursier/v1
+#          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
 
 #      - name: Cache project
 #        uses: actions/cache@v3
@@ -80,11 +79,11 @@ jobs:
           path: node/target/scala-3.*.*/plasma-node-*.jar
           if-no-files-found: error
       
-      - name: Cleanup before cache
-        shell: bash
-        run: |
-          rm -rf "$HOME/.ivy2/local" || true
-          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
-          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
-          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
-          find $HOME/.sbt                              -name "*.lock"               -delete || true
+#      - name: Cleanup before cache
+#        shell: bash
+#        run: |
+#          rm -rf "$HOME/.ivy2/local" || true
+#          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
+#          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
+#          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
+#          find $HOME/.sbt                              -name "*.lock"               -delete || true
